/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	storageiov1alpha1 "github.com/tommenx/storage/pkg/apis/storage.io/v1alpha1"
	versioned "github.com/tommenx/storage/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tommenx/storage/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tommenx/storage/pkg/client/listers/storage.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// StorageLabelInformer provides access to a shared informer and lister for
// StorageLabels.
type StorageLabelInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.StorageLabelLister
}

type storageLabelInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewStorageLabelInformer constructs a new informer for StorageLabel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewStorageLabelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredStorageLabelInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredStorageLabelInformer constructs a new informer for StorageLabel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredStorageLabelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha1().StorageLabels(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.StorageV1alpha1().StorageLabels(namespace).Watch(options)
			},
		},
		&storageiov1alpha1.StorageLabel{},
		resyncPeriod,
		indexers,
	)
}

func (f *storageLabelInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredStorageLabelInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *storageLabelInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&storageiov1alpha1.StorageLabel{}, f.defaultInformer)
}

func (f *storageLabelInformer) Lister() v1alpha1.StorageLabelLister {
	return v1alpha1.NewStorageLabelLister(f.Informer().GetIndexer())
}
