/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tommenx/storage/pkg/apis/storage.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStorageLables implements StorageLableInterface
type FakeStorageLables struct {
	Fake *FakeStorageV1alpha1
	ns   string
}

var storagelablesResource = schema.GroupVersionResource{Group: "storage.io", Version: "v1alpha1", Resource: "storagelables"}

var storagelablesKind = schema.GroupVersionKind{Group: "storage.io", Version: "v1alpha1", Kind: "StorageLable"}

// Get takes name of the storageLable, and returns the corresponding storageLable object, and an error if there is any.
func (c *FakeStorageLables) Get(name string, options v1.GetOptions) (result *v1alpha1.StorageLable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagelablesResource, c.ns, name), &v1alpha1.StorageLable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageLable), err
}

// List takes label and field selectors, and returns the list of StorageLables that match those selectors.
func (c *FakeStorageLables) List(opts v1.ListOptions) (result *v1alpha1.StorageLableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagelablesResource, storagelablesKind, c.ns, opts), &v1alpha1.StorageLableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StorageLableList{ListMeta: obj.(*v1alpha1.StorageLableList).ListMeta}
	for _, item := range obj.(*v1alpha1.StorageLableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storageLables.
func (c *FakeStorageLables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagelablesResource, c.ns, opts))

}

// Create takes the representation of a storageLable and creates it.  Returns the server's representation of the storageLable, and an error, if there is any.
func (c *FakeStorageLables) Create(storageLable *v1alpha1.StorageLable) (result *v1alpha1.StorageLable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagelablesResource, c.ns, storageLable), &v1alpha1.StorageLable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageLable), err
}

// Update takes the representation of a storageLable and updates it. Returns the server's representation of the storageLable, and an error, if there is any.
func (c *FakeStorageLables) Update(storageLable *v1alpha1.StorageLable) (result *v1alpha1.StorageLable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagelablesResource, c.ns, storageLable), &v1alpha1.StorageLable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageLable), err
}

// Delete takes name of the storageLable and deletes it. Returns an error if one occurs.
func (c *FakeStorageLables) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagelablesResource, c.ns, name), &v1alpha1.StorageLable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStorageLables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagelablesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.StorageLableList{})
	return err
}

// Patch applies the patch and returns the patched storageLable.
func (c *FakeStorageLables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StorageLable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagelablesResource, c.ns, name, pt, data, subresources...), &v1alpha1.StorageLable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StorageLable), err
}
