/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/tommenx/storage/pkg/apis/storage.io/v1alpha1"
	scheme "github.com/tommenx/storage/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StorageLablesGetter has a method to return a StorageLableInterface.
// A group's client should implement this interface.
type StorageLablesGetter interface {
	StorageLables(namespace string) StorageLableInterface
}

// StorageLableInterface has methods to work with StorageLable resources.
type StorageLableInterface interface {
	Create(*v1alpha1.StorageLable) (*v1alpha1.StorageLable, error)
	Update(*v1alpha1.StorageLable) (*v1alpha1.StorageLable, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StorageLable, error)
	List(opts v1.ListOptions) (*v1alpha1.StorageLableList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StorageLable, err error)
	StorageLableExpansion
}

// storageLables implements StorageLableInterface
type storageLables struct {
	client rest.Interface
	ns     string
}

// newStorageLables returns a StorageLables
func newStorageLables(c *StorageV1alpha1Client, namespace string) *storageLables {
	return &storageLables{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storageLable, and returns the corresponding storageLable object, and an error if there is any.
func (c *storageLables) Get(name string, options v1.GetOptions) (result *v1alpha1.StorageLable, err error) {
	result = &v1alpha1.StorageLable{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagelables").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StorageLables that match those selectors.
func (c *storageLables) List(opts v1.ListOptions) (result *v1alpha1.StorageLableList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StorageLableList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagelables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storageLables.
func (c *storageLables) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storagelables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storageLable and creates it.  Returns the server's representation of the storageLable, and an error, if there is any.
func (c *storageLables) Create(storageLable *v1alpha1.StorageLable) (result *v1alpha1.StorageLable, err error) {
	result = &v1alpha1.StorageLable{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storagelables").
		Body(storageLable).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storageLable and updates it. Returns the server's representation of the storageLable, and an error, if there is any.
func (c *storageLables) Update(storageLable *v1alpha1.StorageLable) (result *v1alpha1.StorageLable, err error) {
	result = &v1alpha1.StorageLable{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagelables").
		Name(storageLable.Name).
		Body(storageLable).
		Do().
		Into(result)
	return
}

// Delete takes name of the storageLable and deletes it. Returns an error if one occurs.
func (c *storageLables) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagelables").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storageLables) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagelables").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storageLable.
func (c *storageLables) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StorageLable, err error) {
	result = &v1alpha1.StorageLable{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storagelables").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
